
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-assistant-api-config
data:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  HTTPS_ENABLED: "0"  # Disable HTTPS for the Flask app
  FLASK_SECRET_KEY: "secure-random-secret-key-for-session-management"
  SSL_CERT_PATH: "/app/cert.pem"
  SSL_KEY_PATH: "/app/key.pem"
