
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-assistant-api-config
data:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  HTTPS_ENABLED: "0"  # Disable HTTPS for the Flask app
  FLASK_SECRET_KEY: "secure-random-secret-key-for-session-management"
  JWT_SECRET: "change-me-to-a-secure-random-key-in-production"
  JWT_EXPIRATION: "86400"  # Token valid for 24 hours
  SSL_CERT_PATH: "/app/cert.pem"
  SSL_KEY_PATH: "/app/key.pem"
  FRONTEND_URL: "http://localhost:5173"
  GITHUB_CLIENT_ID: "your-real-github-client-id"  # Replace with your GitHub Client ID
  GITHUB_CLIENT_SECRET: "your-real-github-client-secret"  # Replace with your GitHub Client Secret
  GITHUB_REDIRECT_URI: "http://localhost:8000/api/auth/github/callback"
