
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-assistant-api-config
data:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  HTTPS_ENABLED: "1"  # Enable HTTPS for the Flask app
  # SAML SSO Configuration
  SAML_IDP_ENTITY_ID: "https://idp.example.com/saml2/metadata"
  SAML_IDP_SSO_URL: "https://idp.example.com/saml2/sso"
  SAML_IDP_SLO_URL: "https://idp.example.com/saml2/slo"
  SAML_SP_ENTITY_ID: "https://ai-assistant-api/saml/metadata"
  SAML_SP_ACS_URL: "https://ai-assistant-api/saml/acs"
  SAML_SP_SLS_URL: "https://ai-assistant-api/saml/sls"
  # Add any other environment variables needed by your Flask app
