
FROM python:3.9-slim

WORKDIR /app

COPY sample_flask_kubernetes_api.py requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8000"]
