
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
      - name: {{ .Values.ui.name }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.ui.resources.limits.cpu }}
            memory: {{ .Values.ui.resources.limits.memory }}
          requests:
            cpu: {{ .Values.ui.resources.requests.cpu }}
            memory: {{ .Values.ui.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: {{ .Values.global.environment }}
        - name: VITE_API_BASE_URL
          value: {{ .Values.ui.env.VITE_API_BASE_URL | quote }}
