
{{- if .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- range $key, $value := .Values.ui.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  {{- range .Values.ui.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.ui.name }}
            port:
              number: {{ $.Values.ui.service.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.ui.ingress.hosts }}
    - {{ .host }}
    {{- end }}
    secretName: {{ .Values.ui.ingress.tls.secretName }}
  {{- end }}
{{- end }}
